- pkg:maven/dev.keva/config@0.1.1?classifier=sources
- pkg:maven/dev.keva/config@0.1.2?classifier=sources
- pkg:maven/dev.keva/config@0.1.3?classifier=sources
- pkg:maven/dev.keva/config@0.1.4?classifier=sources
- pkg:maven/dev.keva/config@1.0.0-rc0?classifier=sources
