- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@7.1.10
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@7.1.10?classifier=sources
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@7.1.11
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@7.1.11?classifier=sources
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@7.1.12
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@7.1.12?classifier=sources
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@7.1.9
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@7.1.9?classifier=sources
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@8.0.1
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@8.0.1?classifier=sources
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@8.0.2
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@8.0.2?classifier=sources
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@8.0.3
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@8.0.3?classifier=sources
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@8.0.4
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@8.0.4?classifier=sources
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@8.0.5
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@8.0.5?classifier=sources
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@8.0.6
- pkg:maven/org.apache.qpid/qpid-broker-plugins-prometheus-exporter@8.0.6?classifier=sources
