- pkg:maven/com.varwise/prometheus-akka-http_2.13@0.5.0
- pkg:maven/com.varwise/prometheus-akka-http_2.13@0.5.0?classifier=sources
- pkg:maven/com.varwise/prometheus-akka-http_2.13@0.5.1
- pkg:maven/com.varwise/prometheus-akka-http_2.13@0.5.1?classifier=sources
