- pkg:maven/com.github.hiwepy/undertow-metrics-prometheus@1.0.0.RELEASE
- pkg:maven/com.github.hiwepy/undertow-metrics-prometheus@1.0.0.RELEASE?classifier=sources
- pkg:maven/com.github.hiwepy/undertow-metrics-prometheus@2.3.x.20240823.RELEASE
- pkg:maven/com.github.hiwepy/undertow-metrics-prometheus@2.3.x.20240823.RELEASE?classifier=sources
- pkg:maven/com.github.hiwepy/undertow-metrics-prometheus@2.7.x.20240823.RELEASE
- pkg:maven/com.github.hiwepy/undertow-metrics-prometheus@2.7.x.20240823.RELEASE?classifier=sources
