- pkg:maven/io.prometheus/prometheus-metrics-simpleclient-bridge@1.0.0
- pkg:maven/io.prometheus/prometheus-metrics-simpleclient-bridge@1.0.0-alpha-5
- pkg:maven/io.prometheus/prometheus-metrics-simpleclient-bridge@1.0.0-alpha-5?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-simpleclient-bridge@1.0.0-beta-1
- pkg:maven/io.prometheus/prometheus-metrics-simpleclient-bridge@1.0.0-beta-1?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-simpleclient-bridge@1.0.0?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-simpleclient-bridge@1.1.0
- pkg:maven/io.prometheus/prometheus-metrics-simpleclient-bridge@1.1.0?classifier=sources
