- pkg:maven/io.opentelemetry/opentelemetry-exporters-prometheus@0.4.0
- pkg:maven/io.opentelemetry/opentelemetry-exporters-prometheus@0.4.0?classifier=sources
- pkg:maven/io.opentelemetry/opentelemetry-exporters-prometheus@0.4.1
- pkg:maven/io.opentelemetry/opentelemetry-exporters-prometheus@0.4.1?classifier=sources
- pkg:maven/io.opentelemetry/opentelemetry-exporters-prometheus@0.5.0
- pkg:maven/io.opentelemetry/opentelemetry-exporters-prometheus@0.5.0?classifier=sources
- pkg:maven/io.opentelemetry/opentelemetry-exporters-prometheus@0.6.0
- pkg:maven/io.opentelemetry/opentelemetry-exporters-prometheus@0.6.0?classifier=sources
