- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.10.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.11.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.12.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.14.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.15.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.16.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.17.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.18.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.19.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.20.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.21.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.22.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.23.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.6.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.7.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.8.0?classifier=sources
- pkg:maven/org.eclipse.apoapsis.ortserver/tasks@0.9.0?classifier=sources
