- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus-cf@1.10.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus-cf@1.11.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus-cf@1.12.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus-cf@1.13.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus-cf@1.14.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus-cf@1.15.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus-cf@1.15.1?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus-cf@1.16.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus-cf@1.16.1?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus-cf@1.17.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus-cf@1.18.0?classifier=sources
